version: '3.8'

services:
  postgredb:
    # env_file: ./server/.env
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5332:5432"
    volumes:
      - db:/var/lib/postgres

  server:
    depends_on:
      - postgredb
    # env_file: ./server/.env
    build:
      context: ./server
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgredb
    ports:
      - "3001:3001"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"

volumes:
  db:

# docker-compose --env-file ./server/.env  up --build