name: Keep Backend & Supabase Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Keep Render Backend Alive
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          curl -s --fail "$BACKEND_URL" || echo "Backend ping failed"

      - name: Keep Supabase Database Alive
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          curl -s --fail "$SUPABASE_DB_URL" || echo "Database ping failed"
