name: Keep Backend & Supabase Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Keep Render Backend Alive
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          curl -s --fail "$BACKEND_URL" && echo "Backend is alive" || echo "Backend ping failed"

      - name: Keep Supabase Database Alive
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          node -e "
          (async () => {
            const { createClient } = require('@supabase/supabase-js');
            const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
            try {
              const { data, error } = await supabase.from('Users').select('id').limit(1);
              if (error) throw error;
              console.log('Supabase Ping Success:', data);
            } catch (err) {
              console.error('Supabase Ping Failed:', err);
            }
          })();
          "
